using Mauren.Net.Authentication;
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading;
using System.Threading.Tasks;

namespace Mauren.Net
{
    /// <summary>
    /// A service encapsulating authentication and API access
    /// for a given remote endpoint.
    /// </summary>
    /// 
    /// <typeparam name="TCredential">
    /// A type defining credential structure for authentication.
    /// </typeparam>
    /// 
    /// <typeparam name="TAuthenticationState">
    /// A type defining authentication behavior for the service.
    /// </typeparam>
    public abstract partial class ApiService<TCredential, TAuthenticationState> : IApiService
        where TCredential : class, ICredential
        where TAuthenticationState : IAuthenticationState, new()
    {
        /// <summary>
        /// The <see cref="System.Net.Http.HttpClient"/> to use.
        /// </summary>
        protected virtual HttpClient HttpClient { get; }

        /// <summary>
        /// The <typeparamref name="TAuthenticationState"/> to be used to manage authentication state by the service.
        /// </summary>
        protected virtual TAuthenticationState State { get; }

        /// <summary>
        /// The current authorization header provided by the current authentication state.
        /// </summary>
        protected virtual AuthenticationHeaderValue? Authorization => State.Header;

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiService{TCredential, TAuthenticationState}"/> class
        /// with an <see cref="System.Net.Http.HttpClient"/> and <typeparamref name="TCredential"/>.
        /// </summary>
        /// 
        /// <param name="httpClient">
        /// The <see cref="System.Net.Http.HttpClient"/> used to send HTTP requests.
        /// </param>
        /// 
        /// <param name="credential">
        /// The <typeparamref name="TCredential"/> data used for authentication.
        /// </param>
        protected ApiService(HttpClient httpClient, TCredential credential)
        {
            HttpClient = httpClient;
            State = new()
            {
                Credential = credential
            };
        }

        public virtual Uri GetRequestUri(IEndpoint endpoint) => this.HttpClient.At(endpoint);

        /// <summary>
        /// Override this method to provide custom response validation.
        /// </summary>
        /// 
        /// <param name="httpResponseMessage">
        /// The received response message to validate.
        /// </param>
        /// 
        /// <returns>
        /// A <see cref="Task"/> indicating completion.
        /// </returns>
        /// 
        /// <remarks>
        /// The <see langword="base"/> implementation of this method calls <see cref="HttpResponseMessage.EnsureSuccessStatusCode"/>.
        /// </remarks>
        protected virtual async Task ValidateResponse(HttpResponseMessage httpResponseMessage, CancellationToken cancellationToken = default)
        {
            httpResponseMessage.EnsureSuccessStatusCode();
        }

        /// <summary>
        /// Updates the <see cref="State">authentication state</see> via the 
        /// <see cref="HttpClient">HTTP client</see>.
        /// </summary>
        /// 
        /// <param name="cancellationToken">
        /// The cancellation token to cancel operation.
        /// </param>
        /// 
        /// <returns>
        /// A <see cref="Task"/> indicating completion.
        /// </returns>
        public virtual async Task AuthenticateAsync(CancellationToken cancellationToken = default)
        {
            await HttpClient.UpdateAsync(State, cancellationToken, ValidateResponse);
        }

        public virtual async Task<HttpResponseMessage> SendAsync(HttpRequestMessage requestMessage, CancellationToken cancellationToken = default)
        {
            // Check authentication status
            await AuthenticateAsync(cancellationToken);
            // Apply the authorization header generated by the authentication state
            requestMessage.Headers.Authorization = State.Header;
            // Send the HTTP request message via the HTTP client and receive the HTTP response message
            HttpResponseMessage response = await HttpClient.SendAsync(requestMessage, cancellationToken);
            // Validate the HTTP response message
            await ValidateResponse(response, cancellationToken);
            // Return the HTTP response message
            return response;
        }
    }

    public static class ApiServiceExtensions
    {
        public static async Task<HttpResponseMessage> SendAsync<TCredential, TAuthenticationState>(this ApiService<TCredential, TAuthenticationState> apiService, HttpMethod method, Uri requestUri, CancellationToken cancellationToken = default)
            where TCredential : class, ICredential
            where TAuthenticationState : IAuthenticationState, new()
        {
            // Create an HTTP request message
            HttpRequestMessage requestMessage = new(method, requestUri);
            // Send the request message
            return await apiService.SendAsync(requestMessage, cancellationToken);
        }
    }
}